### ISSUE TITLE
bpy_prop_collection[key]: key "MACHIN3tools" not found

### ISSUE THREAD

**Issue by brothermechanic** [machin3io/MACHIN3tools#6]
Hello
I want to try your new F3, but when i activate addon
```
Traceback (most recent call last):
  File "/usr/share/blender/2.80/scripts/modules/addon_utils.py", line 393, in enable
    mod.register()
  File "/home/bm/.config/blender/2.80/scripts/addons/MACHIN3tools-master/__init__.py", line 53, in register
    tool_classlists, tool_keylists, tool_count = get_tools()
  File "/home/bm/.config/blender/2.80/scripts/addons/MACHIN3tools-master/utils/registration.py", line 256, in get_tools
    classlists, keylists, count = get_smart_vert(classlists, keylists, count)
  File "/home/bm/.config/blender/2.80/scripts/addons/MACHIN3tools-master/utils/registration.py", line 338, in get_smart_vert
    if m3.M3_prefs().activate_smart_vert:
  File "/home/bm/.config/blender/2.80/scripts/addons/MACHIN3tools-master/utils/MACHIN3.py", line 209, in M3_prefs
    return bpy.context.user_preferences.addons["MACHIN3tools"].preferences
KeyError: 'bpy_prop_collection[key]: key "MACHIN3tools" not found'
```

**Comment by machin3io** [comment]
Try again, should work now.
