### ISSUE TITLE
Pie menu not working

### ISSUE THREAD

**Issue by winkelchri** [machin3io/MACHIN3tools#8]
Hello,

currently, the edit-pie menu is not working:
```
Traceback (most recent call last):
  File "C:\Users\Chris\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MACHIN3tools\ui\pies.py", line 37, in draw
    pie.operator("machin3.vertex_mode", text="Vertex", icon_value=get_icon('vertex'))
  File "C:\Users\Chris\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MACHIN3tools\utils\ui.py", line 10, in get_icon
    return icons[name].icon_id
TypeError: 'module' object is not subscriptable

location: <unknown location>:-1
```

If I press `TAB`, the menu is just empty.
![grafik](https://user-images.githubusercontent.com/11255205/54827722-f6cc8900-4cb2-11e9-8f03-80b6f6266d87.png)

Unfortunately, I don't exactly understand how the import within the `utils.ui` is working. I assume it should be provisioned within the `utils.registration.register_icons()` function. I only have little to none experience with developing blender addons but know python quite well if you need some more informations.

Used blender version: 41d1582f1df

Thanks a lot for your work!

Regards
Christopher

**Comment by winkelchri** [comment]
It looks like the registration fails due to a missing attribute `VIEW3D_MT_object_context_menu`

```
Exception in module register(): C:\Users\Chris\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MACHIN3tools\__init__.py
Traceback (most recent call last):
  File "c:\blender\2.80\scripts\modules\addon_utils.py", line 393, in enable
    mod.register()
  File "C:\Users\Chris\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MACHIN3tools\__init__.py", line 60, in register
    add_object_context_menu()
  File "C:\Users\Chris\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MACHIN3tools\utils\registration.py", line 209, in add_object_context_menu
    bpy.types.VIEW3D_MT_object_context_menu.prepend(object_context_menu)
AttributeError: 'RNA_Types' object has no attribute 'VIEW3D_MT_object_context_menu'
```

**Comment by winkelchri** [comment]
Never mind. Seemed to be a Blender Bug in this particular version. Since Blender version **faecac0b5e14** working again.
